export const THEME_CHANGED = "THEME_CHANGED";

export const SET_INSTRUMENT = "SET_INSTRUMENT";
export const SET_SOCKET = "SET_SOCKET";

export const UPDATE_TRADE = "UPDATE_TRADE";
export const UPDATE_CLOSING_PRICE = "UPDATE_CLOSING_PRICE";
export const UPDATE_INSTRUMENT_STATE_CHANGE = "UPDATE_INSTRUMENT_STATE_CHANGE";
export const UPDATE_BIDASK = "UPDATE_BIDASK";
export const UPDATE_CLIENT_TRADE = "UPDATE_CLIENT_TRADE";
export const UPDATE_MARKET_ACTIVITY = "UPDATE_MARKET_ACTIVITY";
export const UPDATE_STATIC_THRESHOLD = "UPDATE_STATIC_THRESHOLD";
export const UPDATE_OBSERVER_MESSAGE = "UPDATE_OBSERVER_MESSAGE";

export const SUBSCRIBE = "SUBSCRIBE";
export const UNSUBSCRIBE = "UNSUBSCRIBE";
export const SUBSCRIBE_ALL = "SUBSCRIBE_ALL";
export const UNSUBSCRIBE_ALL = "UNSUBSCRIBE_ALL";

export const SET_CLIENT_ID = "SET_CLIENT_ID";
export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const SET_USER_ACCOUNT_INFO = "SET_USER_ACCOUNT_INFO";
export const UPDATE_USER_ACCOUNT_INFO = "UPDATE_USER_ACCOUNT_INFO";
export const LOGOUT = "LOGOUT";

export const OPEN_TRADE_MODAL = "OPEN_TRADE_MODAL";
export const CLOSE_TRADE_MODAL = "CLOSE_TRADE_MODAL";

export const ENQUEUE_SNACKBAR = "ENQUEUE_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const REMOVE_SNACKBAR = "REMOVE_SNACKBAR";
// export const NOTIFY_SUCCESS = "NOTIFY_SUCCESS";
// export const NOTIFY_ERROR = "NOTIFY_ERROR";

export const SET_WATCHLIST = "SET_WATCHLIST";

export const CMD_PUSHER_CONNECT = "CMD_PUSHER_CONNECT";
export const CMD_PUSHER_SUBSCRIBE = "CMD_PUSHER_SUBSCRIBE";
export const CMD_PUSHER_UNSUBSCRIBE = "CMD_PUSHER_UNSUBSCRIBE";
export const CMD_PUSHER_SUBSCRIBE_ALL = "CMD_PUSHER_SUBSCRIBE_ALL";
export const CMD_PUSHER_UNSUBSCRIBE_ALL = "CMD_PUSHER_UNSUBSCRIBE_ALL";

export const CST_PUSHER_SUBSCRIBE = "CST_PUSHER_SUBSCRIBE";
export const CST_PUSHER_UNSUBSCRIBE = "CST_PUSHER_UNSUBSCRIBE";

export const MKD_PUSHER_AUTHENTICATE = "MKD_PUSHER_AUTHENTICATE";
export const MKD_PUSHER_LOGOUT = "MKD_PUSHER_LOGOUT";
export const MKD_PUSHER_SUBSCRIBE = "MKD_PUSHER_SUBSCRIBE";
export const MKD_PUSHER_UNSUBSCRIBE = "MKD_PUSHER_UNSUBSCRIBE";
export const MKD_SET_INIT_DATA = "MKD_SET_INIT_DATA";
export const MKD_SET_DATA = "MKD_SET_DATA";

export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_TRADES_SUCCESS = "FETCH_TRADES_SUCCESS";
export const FETCH_PORTFOLIO_SUCCESS = "FETCH_PORTFOLIO_SUCCESS";
export const FETCH_DRAFT_ORDERS_SUCCESS = "FETCH_DRAFT_ORDERS_SUCCESS";

export const ADD_ORDER = "ADD_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const REMOVE_ORDER = "REMOVE_ORDER";

export const SET_ACCOUNT_STATE = "SET_ACCOUNT_STATE";

export const TRADE_REGISTER = "TRADE_REGISTER";
export const TRADE_CANCEL = "TRADE_CANCEL";

export const UPDATE_ASSET = "UPDATE_ASSET";
export const REMOVE_ASSET = "REMOVE_ASSET";

export const SET_IPO_INSTRUMENTS = "SET_IPO_INSTRUMENTS";
export const SET_UNDER_CAUTION_INSTRUMENTS = "SET_UNDER_CAUTION_INSTRUMENTS";

export const SET_PERMISSIONS = "SET_PERMISSIONS";
export const SET_BACK_BUTTON = "SET_BACK_BUTTON";
export const SET_PAGE_TITLE = "SET_PAGE_TITLE";

export const ADD_WIDGET_ITEM = "ADD_WIDGET_ITEM";
export const REMOVE_WIDGET_ITEM = "REMOVE_WIDGET_ITEM";
export const SET_WIDGET_ITEMS = "SET_WIDGET_ITEMS";

export const SET_TRADE_SIDE = "SET_TRADE_SIDE";

export const SET_IS_TOUR_OPEN = "SET_IS_TOUR_OPEN";

export const SET_ALGORITM_NOTIFICATION = "SET_ALGORITM_NOTIFICATION";
export const CLEAR_ALGORITM_NOTIFICATION = "CLEAR_ALGORITM_NOTIFICATION";
