const templates = [
  {
    title: "قالب کلاسیک",
    widgets: [
      {
        title: "دیده‌بان پیشرفته",
        i: "AdvancedWatchlist",
        w: 7,
        h: 18,
        x: 0,
        y: 0,
        minW: 6,
        maxW: 12,
        minH: 8,
        maxH: 34,
        props: { advanced: true },
      },
      {
        title: "سفارشات",
        i: "Orders",
        w: 8,
        h: 11,
        x: 0,
        y: 0,
        minW: 6,
        maxW: 12,
        minH: 8,
        maxH: 34,
        component: { compare: null, displayName: "Connect(Footer)" },
        props: { widget: true },
      },
      {
        title: "اطلاعات نماد",
        i: "Instrument",
        w: 4,
        h: 15,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 5,
        minH: 5,
        maxH: 18,
        component: { compare: null, displayName: "Connect(Instrument)" },
        props: { widget: true },
      },
      {
        title: "صف خرید و فروش",
        i: "Bidask",
        w: 3,
        h: 10,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 6,
        minH: 6,
        maxH: 22,
        component: {
          type: { compare: null, displayName: "Connect(Bidask)" },
          compare: null,
        },
        props: { widget: true },
      },
      {
        title: "حقیقی و حقوقی",
        i: "ClientTrade",
        w: 3,
        h: 6,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 7,
        minH: 6,
        maxH: 10,
        component: { compare: null, displayName: "Connect(ClientTrade)" },
        props: { widget: true },
      },
      {
        title: "نمودار",
        i: "TradeChart",
        w: 3,
        h: 11,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 7,
        minH: 8,
        maxH: 18,
        component: { compare: null, displayName: "Connect(TradeChart)" },
        props: { width: 500, height: 220, widget: true },
      },
      {
        title: "فرم خرید و فروش افقی",
        i: "HorizontalTrade",
        w: 8,
        h: 5,
        x: 0,
        y: 0,
        minW: 6,
        maxW: 12,
        minH: 5,
        maxH: 5,
        component: { compare: null, displayName: "Connect(Trade)" },
        props: { widget: true, buyPower: true, horizontal: true, buy: true },
      },
    ],
    layouts: {
      lg: [
        {
          w: 12,
          h: 14,
          x: 0,
          y: 0,
          i: "AdvancedWatchlist",
          minW: 6,
          maxW: 12,
          minH: 8,
          maxH: 34,
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 10,
          x: 0,
          y: 37,
          i: "Orders",
          minW: 6,
          maxW: 12,
          minH: 8,
          maxH: 34,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 18,
          x: 8,
          y: 14,
          i: "Instrument",
          minW: 3,
          maxW: 5,
          minH: 5,
          maxH: 18,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 10,
          x: 4,
          y: 14,
          i: "Bidask",
          minW: 2,
          maxW: 6,
          minH: 6,
          maxH: 22,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 8,
          x: 4,
          y: 24,
          i: "ClientTrade",
          minW: 2,
          maxW: 7,
          minH: 6,
          maxH: 10,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 18,
          x: 0,
          y: 14,
          i: "TradeChart",
          minW: 3,
          maxW: 7,
          minH: 8,
          maxH: 18,
          moved: false,
          static: false,
        },
        {
          w: 12,
          h: 5,
          x: 0,
          y: 32,
          i: "HorizontalTrade",
          minW: 6,
          maxW: 12,
          minH: 5,
          maxH: 5,
          moved: false,
          static: false,
        },
      ],
    },
  },
  {
    title: "قالب مدرن",
    widgets: [
      {
        title: "جستجو",
        i: "Search",
        w: 2,
        h: 5,
        x: 0,
        y: 0,
        minW: 1,
        maxW: 4,
        minH: 5,
        maxH: 5,
        component: { compare: null, displayName: "Connect(InstrumentLookup)" },
        props: { widget: true, value: "", placeholder: "جستجوی نماد" },
      },
      {
        title: "سفارشات",
        i: "Orders",
        w: 8,
        h: 11,
        x: 0,
        y: 0,
        minW: 6,
        maxW: 12,
        minH: 8,
        maxH: 34,
        component: { compare: null, displayName: "Connect(Footer)" },
        props: { widget: true },
      },
      {
        title: "دیده‌بان پیشرفته",
        i: "AdvancedWatchlist",
        w: 7,
        h: 18,
        x: 0,
        y: 0,
        minW: 6,
        maxW: 12,
        minH: 8,
        maxH: 42,
        props: { advanced: true },
      },
      {
        title: "اطلاعات نماد",
        i: "Instrument",
        w: 4,
        h: 15,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 5,
        minH: 5,
        maxH: 18,
        component: { compare: null, displayName: "Connect(Instrument)" },
        props: { widget: true },
      },
      {
        title: "صف خرید و فروش",
        i: "Bidask",
        w: 3,
        h: 10,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 6,
        minH: 6,
        maxH: 22,
        component: {
          type: { compare: null, displayName: "Connect(Bidask)" },
          compare: null,
        },
        props: { widget: true },
      },
      {
        title: "حقیقی و حقوقی",
        i: "ClientTrade",
        w: 3,
        h: 6,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 7,
        minH: 6,
        maxH: 10,
        component: { compare: null, displayName: "Connect(ClientTrade)" },
        props: { widget: true },
      },
      {
        title: "بازه قیمتی",
        i: "TradeRange",
        w: 3,
        h: 6,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 7,
        minH: 6,
        maxH: 10,
        props: { widget: true },
      },
      {
        title: "واچ لیست",
        i: "Watchlist",
        w: 2,
        h: 18,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 4,
        minH: 8,
        maxH: 42,
        props: { widget: true },
      },
      {
        title: "فرم خرید و فروش",
        i: "Trade",
        w: 5,
        h: 11,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 7,
        minH: 8,
        maxH: 15,
        component: { compare: null, displayName: "Connect(Trade)" },
        props: { widget: true, buyPower: true },
      },
    ],
    layouts: {
      lg: [
        {
          w: 2,
          h: 5,
          x: 0,
          y: 0,
          i: "Search",
          minW: 1,
          maxW: 4,
          minH: 5,
          maxH: 5,
          moved: false,
          static: false,
        },
        {
          w: 7,
          h: 18,
          x: 5,
          y: 25,
          i: "Orders",
          minW: 6,
          maxW: 12,
          minH: 8,
          maxH: 34,
          moved: false,
          static: false,
        },
        {
          w: 7,
          h: 25,
          x: 5,
          y: 0,
          i: "AdvancedWatchlist",
          minW: 6,
          maxW: 12,
          minH: 8,
          maxH: 42,
          moved: false,
          static: false,
        },
        {
          w: 3,
          h: 17,
          x: 2,
          y: 0,
          i: "Instrument",
          minW: 3,
          maxW: 5,
          minH: 5,
          maxH: 18,
          moved: false,
          static: false,
        },
        {
          w: 3,
          h: 12,
          x: 2,
          y: 17,
          i: "Bidask",
          minW: 2,
          maxW: 6,
          minH: 6,
          maxH: 22,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 10,
          x: 0,
          y: 33,
          i: "ClientTrade",
          minW: 2,
          maxW: 7,
          minH: 6,
          maxH: 10,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 10,
          x: 0,
          y: 23,
          i: "TradeRange",
          minW: 2,
          maxW: 7,
          minH: 6,
          maxH: 10,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 18,
          x: 0,
          y: 5,
          i: "Watchlist",
          minW: 2,
          maxW: 4,
          minH: 8,
          maxH: 42,
          moved: false,
          static: false,
        },
        {
          w: 3,
          h: 14,
          x: 2,
          y: 29,
          i: "Trade",
          minW: 3,
          maxW: 7,
          minH: 8,
          maxH: 15,
          moved: false,
          static: false,
        },
      ],
    },
  },
  {
    title: "قالب استاندارد ",
    widgets: [
      {
        title: "سفارشات",
        i: "Orders",
        w: 8,
        h: 11,
        x: 0,
        y: 0,
        minW: 6,
        maxW: 12,
        minH: 8,
        maxH: 34,
        component: { compare: null, displayName: "Connect(Footer)" },
        props: { widget: true },
      },
      {
        title: "پیام ناظر",
        i: "ObserverMessage",
        w: 2,
        h: 20,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 5,
        minH: 6,
        maxH: 34,
        component: {
          compare: null,
          displayName: "Connect(WithWidth(ObserverMessage))",
        },
        props: { widget: true },
      },
      {
        title: "واچ لیست",
        i: "Watchlist",
        w: 2,
        h: 18,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 4,
        minH: 8,
        maxH: 42,
        props: { widget: true },
      },
      {
        title: "جستجو",
        i: "Search",
        w: 2,
        h: 5,
        x: 0,
        y: 0,
        minW: 1,
        maxW: 4,
        minH: 5,
        maxH: 5,
        component: { compare: null, displayName: "Connect(InstrumentLookup)" },
        props: { widget: true, value: "", placeholder: "جستجوی نماد" },
      },
      {
        title: "اطلاعات نماد",
        i: "Instrument",
        w: 4,
        h: 15,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 5,
        minH: 5,
        maxH: 18,
        component: { compare: null, displayName: "Connect(Instrument)" },
        props: { widget: true },
      },
      {
        title: "صف خرید و فروش",
        i: "Bidask",
        w: 3,
        h: 10,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 6,
        minH: 6,
        maxH: 22,
        component: {
          type: { compare: null, displayName: "Connect(Bidask)" },
          compare: null,
        },
        props: { widget: true },
      },
      {
        title: "حقیقی و حقوقی",
        i: "ClientTrade",
        w: 3,
        h: 6,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 7,
        minH: 6,
        maxH: 10,
        component: { compare: null, displayName: "Connect(ClientTrade)" },
        props: { widget: true },
      },
      {
        title: "بازه قیمتی",
        i: "TradeRange",
        w: 3,
        h: 6,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 7,
        minH: 6,
        maxH: 10,
        props: { widget: true },
      },
      {
        title: "فرم خرید و فروش",
        i: "Trade",
        w: 5,
        h: 11,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 7,
        minH: 8,
        maxH: 15,
        component: { compare: null, displayName: "Connect(Trade)" },
        props: { widget: true, buyPower: true },
      },
    ],
    layouts: {
      lg: [
        {
          w: 10,
          h: 19,
          x: 0,
          y: 24,
          i: "Orders",
          minW: 6,
          maxW: 12,
          minH: 8,
          maxH: 34,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 15,
          x: 10,
          y: 28,
          i: "ObserverMessage",
          minW: 2,
          maxW: 5,
          minH: 6,
          maxH: 34,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 23,
          x: 10,
          y: 5,
          i: "Watchlist",
          minW: 2,
          maxW: 4,
          minH: 8,
          maxH: 42,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 5,
          x: 10,
          y: 0,
          i: "Search",
          minW: 1,
          maxW: 4,
          minH: 5,
          maxH: 5,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 15,
          x: 6,
          y: 0,
          i: "Instrument",
          minW: 3,
          maxW: 5,
          minH: 5,
          maxH: 18,
          moved: false,
          static: false,
        },
        {
          w: 3,
          h: 15,
          x: 3,
          y: 0,
          i: "Bidask",
          minW: 2,
          maxW: 6,
          minH: 6,
          maxH: 22,
          moved: false,
          static: false,
        },
        {
          w: 5,
          h: 9,
          x: 5,
          y: 15,
          i: "ClientTrade",
          minW: 2,
          maxW: 7,
          minH: 6,
          maxH: 10,
          moved: false,
          static: false,
        },
        {
          w: 5,
          h: 9,
          x: 0,
          y: 15,
          i: "TradeRange",
          minW: 2,
          maxW: 7,
          minH: 6,
          maxH: 10,
          moved: false,
          static: false,
        },
        {
          w: 3,
          h: 15,
          x: 0,
          y: 0,
          i: "Trade",
          minW: 3,
          maxW: 7,
          minH: 8,
          maxH: 15,
          moved: false,
          static: false,
        },
      ],
    },
  },
  {
    title: "قالب ساده و سریع",
    widgets: [
      {
        title: "جستجو",
        i: "Search",
        w: 3,
        h: 5,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 4,
        minH: 5,
        maxH: 5,
        component: { compare: null, displayName: "Connect(InstrumentLookup)" },
        props: { widget: true, value: "", placeholder: "جستجوی نماد" },
      },
      {
        title: "صف خرید و فروش",
        i: "Bidask",
        w: 3,
        h: 10,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 6,
        minH: 6,
        maxH: 22,
        component: {
          type: { compare: null, displayName: "Connect(Bidask)" },
          compare: null,
        },
        props: { widget: true },
      },
      {
        title: "واچ لیست",
        i: "Watchlist",
        w: 2,
        h: 18,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 4,
        minH: 8,
        maxH: 42,
        props: { widget: true },
      },
      {
        title: "اطلاعات نماد",
        i: "Instrument",
        w: 4,
        h: 15,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 5,
        minH: 5,
        maxH: 17,
        component: { compare: null, displayName: "Connect(Instrument)" },
        props: { widget: true },
      },
      {
        title: "فرم خرید و فروش",
        i: "Trade",
        w: 5,
        h: 11,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 7,
        minH: 8,
        maxH: 15,
        component: { compare: null, displayName: "Connect(Trade)" },
        props: { widget: true, buyPower: true },
      },
    ],
    layouts: {
      lg: [
        {
          w: 2,
          h: 5,
          x: 7,
          y: 0,
          i: "Search",
          minW: 2,
          maxW: 4,
          minH: 5,
          maxH: 5,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 10,
          x: 3,
          y: 0,
          i: "Bidask",
          minW: 2,
          maxW: 6,
          minH: 6,
          maxH: 22,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 36,
          x: 7,
          y: 5,
          i: "Watchlist",
          minW: 2,
          maxW: 4,
          minH: 8,
          maxH: 42,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 17,
          x: 3,
          y: 10,
          i: "Instrument",
          minW: 3,
          maxW: 5,
          minH: 5,
          maxH: 17,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 14,
          x: 3,
          y: 27,
          i: "Trade",
          minW: 3,
          maxW: 7,
          minH: 8,
          maxH: 15,
          moved: false,
          static: false,
        },
      ],
    },
  },
  {
    title: "قالب ویژه ",
    widgets: [
      {
        title: "سفارشات",
        i: "Orders",
        w: 8,
        h: 11,
        x: 0,
        y: 0,
        minW: 6,
        maxW: 12,
        minH: 8,
        maxH: 34,
        component: { compare: null, displayName: "Connect(Footer)" },
        props: { widget: true },
      },
      {
        title: "جستجو",
        i: "Search",
        w: 2,
        h: 5,
        x: 0,
        y: 0,
        minW: 1,
        maxW: 4,
        minH: 5,
        maxH: 5,
        component: { compare: null, displayName: "Connect(InstrumentLookup)" },
        props: { widget: true, value: "", placeholder: "جستجوی نماد" },
      },
      {
        title: "واچ لیست",
        i: "Watchlist",
        w: 2,
        h: 18,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 4,
        minH: 8,
        maxH: 42,
        props: { widget: true },
      },
      {
        title: "اطلاعات نماد",
        i: "Instrument",
        w: 4,
        h: 15,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 5,
        minH: 5,
        maxH: 18,
        component: { compare: null, displayName: "Connect(Instrument)" },
        props: { widget: true },
      },
      {
        title: "صف خرید و فروش",
        i: "Bidask",
        w: 3,
        h: 10,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 6,
        minH: 6,
        maxH: 22,
        component: {
          type: { compare: null, displayName: "Connect(Bidask)" },
          compare: null,
        },
        props: { widget: true },
      },
      {
        title: "بازه قیمتی",
        i: "TradeRange",
        w: 3,
        h: 6,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 7,
        minH: 6,
        maxH: 10,
        props: { widget: true },
      },
      {
        title: "حقیقی و حقوقی",
        i: "ClientTrade",
        w: 3,
        h: 6,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 7,
        minH: 6,
        maxH: 10,
        component: { compare: null, displayName: "Connect(ClientTrade)" },
        props: { widget: true },
      },
      {
        title: "فرم خرید و فروش",
        i: "Trade",
        w: 5,
        h: 11,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 7,
        minH: 8,
        maxH: 15,
        component: { compare: null, displayName: "Connect(Trade)" },
        props: { widget: true, buyPower: true },
      },
      {
        title: "پیام ناظر",
        i: "ObserverMessage",
        w: 2,
        h: 20,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 5,
        minH: 6,
        maxH: 34,
        component: {
          compare: null,
          displayName: "Connect(WithWidth(ObserverMessage))",
        },
        props: { widget: true },
      },
    ],
    layouts: {
      lg: [
        {
          w: 10,
          h: 11,
          x: 0,
          y: 31,
          i: "Orders",
          minW: 6,
          maxW: 12,
          minH: 8,
          maxH: 34,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 5,
          x: 10,
          y: 0,
          i: "Search",
          minW: 1,
          maxW: 4,
          minH: 5,
          maxH: 5,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 37,
          x: 10,
          y: 5,
          i: "Watchlist",
          minW: 2,
          maxW: 4,
          minH: 8,
          maxH: 42,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 17,
          x: 6,
          y: 0,
          i: "Instrument",
          minW: 3,
          maxW: 5,
          minH: 5,
          maxH: 18,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 14,
          x: 6,
          y: 17,
          i: "Bidask",
          minW: 2,
          maxW: 6,
          minH: 6,
          maxH: 22,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 9,
          x: 2,
          y: 0,
          i: "TradeRange",
          minW: 2,
          maxW: 7,
          minH: 6,
          maxH: 10,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 8,
          x: 2,
          y: 9,
          i: "ClientTrade",
          minW: 2,
          maxW: 7,
          minH: 6,
          maxH: 10,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 14,
          x: 2,
          y: 17,
          i: "Trade",
          minW: 3,
          maxW: 7,
          minH: 8,
          maxH: 15,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 31,
          x: 0,
          y: 0,
          i: "ObserverMessage",
          minW: 2,
          maxW: 5,
          minH: 6,
          maxH: 34,
          moved: false,
          static: false,
        },
      ],
    },
  },
  {
    title: "قالب  چپ به راست",
    widgets: [
      {
        title: "سفارشات",
        i: "Orders",
        w: 8,
        h: 11,
        x: 0,
        y: 0,
        minW: 6,
        maxW: 12,
        minH: 8,
        maxH: 34,
        component: { compare: null, displayName: "Connect(Footer)" },
        props: { widget: true },
      },
      {
        title: "نمودار",
        i: "TradeChart",
        w: 3,
        h: 11,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 7,
        minH: 8,
        maxH: 18,
        component: { compare: null, displayName: "Connect(TradeChart)" },
        props: { width: 500, height: 220, widget: true },
      },
      {
        title: "فرم خرید و فروش",
        i: "Trade",
        w: 5,
        h: 11,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 7,
        minH: 8,
        maxH: 15,
        component: { compare: null, displayName: "Connect(Trade)" },
        props: { widget: true, buyPower: true },
      },
      {
        title: "صف خرید و فروش",
        i: "Bidask",
        w: 3,
        h: 10,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 6,
        minH: 6,
        maxH: 22,
        component: {
          type: { compare: null, displayName: "Connect(Bidask)" },
          compare: null,
        },
        props: { widget: true },
      },
      {
        title: "اطلاعات نماد",
        i: "Instrument",
        w: 4,
        h: 15,
        x: 0,
        y: 0,
        minW: 3,
        maxW: 5,
        minH: 5,
        maxH: 18,
        component: { compare: null, displayName: "Connect(Instrument)" },
        props: { widget: true },
      },
      {
        title: "حقیقی و حقوقی",
        i: "ClientTrade",
        w: 3,
        h: 6,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 7,
        minH: 6,
        maxH: 10,
        component: { compare: null, displayName: "Connect(ClientTrade)" },
        props: { widget: true },
      },
      {
        title: "جستجو",
        i: "Search",
        w: 2,
        h: 5,
        x: 0,
        y: 0,
        minW: 1,
        maxW: 4,
        minH: 5,
        maxH: 5,
        component: { compare: null, displayName: "Connect(InstrumentLookup)" },
        props: { widget: true, value: "", placeholder: "جستجوی نماد" },
      },
      {
        title: "واچ لیست",
        i: "Watchlist",
        w: 2,
        h: 18,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 4,
        minH: 8,
        maxH: 42,
        props: { widget: true },
      },
      {
        title: "بازه قیمتی",
        i: "TradeRange",
        w: 3,
        h: 6,
        x: 0,
        y: 0,
        minW: 2,
        maxW: 7,
        minH: 6,
        maxH: 10,
        props: { widget: true },
      },
    ],
    layouts: {
      lg: [
        {
          w: 12,
          h: 11,
          x: 0,
          y: 31,
          i: "Orders",
          minW: 6,
          maxW: 12,
          minH: 5,
          maxH: 20,
          moved: false,
          static: false,
        },
        {
          w: 3,
          h: 14,
          x: 9,
          y: 17,
          i: "TradeChart",
          minW: 2,
          maxW: 7,
          minH: 8,
          maxH: 18,
          moved: false,
          static: false,
        },
        {
          w: 4,
          h: 14,
          x: 5,
          y: 17,
          i: "Trade",
          minW: 3,
          maxW: 7,
          minH: 8,
          maxH: 15,
          moved: false,
          static: false,
        },
        {
          w: 3,
          h: 14,
          x: 2,
          y: 17,
          i: "Bidask",
          minW: 2,
          maxW: 6,
          minH: 6,
          maxH: 22,
          moved: false,
          static: false,
        },
        {
          w: 3,
          h: 17,
          x: 2,
          y: 0,
          i: "Instrument",
          minW: 3,
          maxW: 5,
          minH: 5,
          maxH: 18,
          moved: false,
          static: false,
        },
        {
          w: 7,
          h: 8,
          x: 5,
          y: 9,
          i: "ClientTrade",
          minW: 2,
          maxW: 7,
          minH: 6,
          maxH: 10,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 5,
          x: 0,
          y: 0,
          i: "Search",
          minW: 1,
          maxW: 4,
          minH: 5,
          maxH: 5,
          moved: false,
          static: false,
        },
        {
          w: 2,
          h: 26,
          x: 0,
          y: 5,
          i: "Watchlist",
          minW: 2,
          maxW: 4,
          minH: 8,
          maxH: 42,
          moved: false,
          static: false,
        },
        {
          w: 7,
          h: 9,
          x: 5,
          y: 0,
          i: "TradeRange",
          minW: 2,
          maxW: 7,
          minH: 6,
          maxH: 10,
          moved: false,
          static: false,
        },
      ],
    },
  },
];

export default templates;
