import Bidask from "../../components/bidask/bidask";
import ClientTrade from "../../components/clientTrade/clientTrade";
import Range from "../../components/range/range";
import ObserverMessage from "../../components/observerMessage/observerMessage";
import Trade from "../../components/trade/trade";
import TradeChart from "../../components/tradeChart/tradeChart";
import Footer from "../../components/footer/footer";
import WatchlistPane from "../../components/watchlistPane/watchlistPane";
import Instrument from "../../components/instrument/instrument";
import InstrumentLookup from "../../components/UI/instrumentLookup/instrumentLookup";
import WidgetTypes from "../../enums/widgetTypes";

const widgets = [
  {
    title: "واچ لیست",
    i: WidgetTypes.Watchlist,
    w: 2,
    h: 18,
    x: 0,
    y: 0,
    minW: 2,
    maxW: 4,
    minH: 8,
    maxH: 42,
    component: WatchlistPane,
    props: { widget: true },
  },
  {
    title: "اطلاعات نماد",
    i: WidgetTypes.Instrument,
    w: 4,
    h: 15,
    x: 0,
    y: 0,
    minW: 3,
    maxW: 5,
    minH: 5,
    maxH: 18,
    component: Instrument,
    props: { widget: true },
  },
  {
    title: "صف خرید و فروش",
    i: WidgetTypes.Bidask,
    w: 3,
    h: 10,
    x: 0,
    y: 0,
    minW: 2,
    maxW: 6,
    minH: 6,
    maxH: 22,
    component: Bidask,
    props: { widget: true },
  },
  {
    title: "حقیقی و حقوقی",
    i: WidgetTypes.ClientTrade,
    w: 3,
    h: 6,
    x: 0,
    y: 0,
    minW: 2,
    maxW: 7,
    minH: 6,
    maxH: 10,
    component: ClientTrade,
    props: { widget: true },
  },
  {
    title: "بازه قیمتی",
    i: WidgetTypes.TradeRange,
    w: 3,
    h: 6,
    x: 0,
    y: 0,
    minW: 2,
    maxW: 7,
    minH: 6,
    maxH: 10,
    component: Range,
    props: { widget: true },
  },
  {
    title: "پیام ناظر",
    i: WidgetTypes.ObserverMessage,
    w: 2,
    h: 20,
    x: 0,
    y: 0,
    minW: 2,
    maxW: 5,
    minH: 6,
    maxH: 34,
    component: ObserverMessage,
    props: { widget: true },
  },
  {
    title: "فرم خرید و فروش",
    i: WidgetTypes.Trade,
    w: 5,
    h: 11,
    x: 0,
    y: 0,
    minW: 3,
    maxW: 7,
    minH: 8,
    maxH: 15,
    component: Trade,
    props: { widget: true, buyPower: true },
  },
  {
    title: "فرم خرید و فروش افقی",
    i: WidgetTypes.HorizontalTrade,
    w: 8,
    h: 5,
    x: 0,
    y: 0,
    minW: 6,
    maxW: 12,
    minH: 5,
    maxH: 5,
    component: Trade,
    props: { widget: true, buyPower: true, horizontal: true, buy: true },
  },
  {
    title: "نمودار",
    i: WidgetTypes.TradeChart,
    w: 3,
    h: 12,
    x: 0,
    y: 0,
    minW: 2,
    maxW: 7,
    minH: 8,
    maxH: 18,
    component: TradeChart,
    props: { width: 500, height: 220, widget: true },
  },
  {
    title: "سفارشات",
    i: WidgetTypes.Orders,
    w: 8,
    h: 11,
    x: 0,
    y: 0,
    minW: 6,
    maxW: 12,
    minH: 8,
    maxH: 34,
    component: Footer,
    props: { widget: true },
  },
  {
    title: "جستجو",
    i: WidgetTypes.Search,
    w: 2,
    h: 5,
    x: 0,
    y: 0,
    minW: 1,
    maxW: 4,
    minH: 5,
    maxH: 5,
    component: InstrumentLookup,
    props: { widget: true, value: "", placeholder: "جستجوی نماد" },
  },
  {
    title: "دیده‌بان پیشرفته",
    i: WidgetTypes.AdvancedWatchlist,
    w: 7,
    h: 18,
    x: 0,
    y: 0,
    minW: 6,
    maxW: 12,
    minH: 8,
    maxH: 42,
    component: WatchlistPane,
    props: { advanced: true },
  },
];

export default widgets;
